# Generated by Django 3.2.16 on 2022-12-18 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userportfolio',
            name='crypto_category',
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='crypto_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
