# Generated by Django 3.2.16 on 2022-12-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('common', '0004_alter_userportfolio_crypto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='crypto_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
