# Generated by Django 3.2.16 on 2022-12-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_userportfolio_crypto_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='crypto_product',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='crypto_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
