# Generated by Django 3.2.16 on 2022-12-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20221219_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
