# Generated by Django 3.2.16 on 2023-07-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20230627_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(db_column='order_quantity', default=1),
        ),
    ]
